### ISSUE TITLE
Display CPU, Memory and Disk usage in the Tmux status bar

### ISSUE THREAD

**Issue by Huy-Thai** [hendrikmi/tmux-cpu-mem-monitor#10]
Hi @hendrikmi,

First of all, thank you for creating this amazing package—it’s really impressive!  

However, I’m facing an issue. I followed the configuration steps as instructed, but the information displayed on the status bar doesn’t seem to be working. Could you help me resolve this?  

For context, I’m configuring it on a Linux (Ubuntu) operating system.
![Screenshot 2024-11-29 at 09 56 08](https://github.com/user-attachments/assets/01b8fa56-22b9-4aa2-9089-3bf4556e4395)

Thanks.

**Comment by hendrikmi** [comment]
Hi @Huy-Thai! 👋

Could you share your tmux config? I'm sure we can get it to work :)

Also, just to make sure: Do you have Python3 installed?

**Comment by Huy-Thai** [comment]
Hi @hendrikmi,

I think maybe python3 env is not working
I will double check and reply to you.

Thanks.

**Comment by Huy-Thai** [comment]
Hi @hendrikmi,

I'm fixed, due to the environment configuration on my computer.
Thanks for taking the time to reply me.

Regards.
